# Generated by Django 4.0 on 2021-12-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_homework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='is_finish',
            new_name='is_finished',
        ),
    ]
